[versions]
geary = "0.20.114"
protocolburrito = "0.5.38"

[libraries]
protocolburrito = { module = "com.mineinabyss:protocolburrito", version.ref = "protocolburrito" }
geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
