[versions]
protocolburrito = "0.6.2"
gearyPaper = "0.23.6"

[libraries]
protocolburrito = { module = "com.mineinabyss:protocolburrito", version.ref = "protocolburrito" }
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "gearyPaper" }
